name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello macOS world action
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: List CPU features
      run: |
        sysctl kern.hv_support
        sysctl machdep.cpu.features
    - name: Install Docker Desktop
      run: |
        sudo ls
        echo "Downloading DMG."
        curl -Lo docker.dmg https://download.docker.com/mac/edge/41561/Docker.dmg
        echo "Extract DMG."
        hdiutil attach docker.dmg
        (cd /Volumes/Docker/ ; cp -av Docker.app /Applications/Docker.app)
        hdiutil detach /Volumes/Docker/
        echo "Install Docker."
        sudo /Applications/Docker.app/Contents/MacOS/Docker --quit-after-install --unattended || true
    - name: Start Docker
      run: |
        echo "Start Docker."
        sh -c "sudo /Applications/Docker.app/Contents/MacOS/Docker --install-privileged-components --unattended" &
        echo "Wait a little bit..."
        sleep 100
        sudo docker version
        sudo docker run hello-world
        sudo docker images
      
    - name: Build image
      run: sudo docker build -t hello .
    - name: Run container
      run: sudo docker run -e MY_NAME hello
      env:
        MY_NAME: "Mona"
