name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello windows world action
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./action-a
      env:
        MY_NAME: "Mona"